from __future__ import annotations
from typing import Protocol, Any, Optional
import pandas as pd


class BrokerBase(Protocol):
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...

    def account_summary(self) -> Any: ...
    def positions(self) -> Any: ...

    def get_historical(self, symbol: str, start: str, end: str,
                       timeframe: str, adjustments: Optional[str] = None) -> pd.DataFrame: ...

    def subscribe_ticks(self, symbols: list[str], on_tick: Optional[callable] = None) -> Any: ...
    def unsubscribe(self, handle: Any) -> None: ...

    def place_order(self, symbol: str, side: str, qty: int, order_type: str,
                    limit: Optional[float] = None, stop: Optional[float] = None,
                    tif: str = 'DAY', meta: Optional[dict] = None) -> Any: ...
    def cancel_order(self, order_id: Any) -> None: ...
    def order_status(self, order_id: Any) -> dict: ...


class DataNormalization(Protocol):
    def normalize_ohlcv(self, df: pd.DataFrame) -> pd.DataFrame: ...
    def normalize_tick(self, event: Any) -> dict: ...
    def normalize_order(self, order: Any) -> dict: ...


